In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size 
voc_size=10000


In [4]:
## onehot representation 
one_hot_repr=[one_hot(word,voc_size)for word in sent]

In [5]:
one_hot_repr

[[9088, 5739, 7350, 9803],
 [9088, 5739, 7350, 487],
 [9088, 1182, 7350, 8539],
 [3160, 3908, 1782, 700, 5473],
 [3160, 3908, 1782, 700, 2116],
 [2230, 9088, 6185, 7350, 9516],
 [3584, 5354, 7856, 700]]

In [6]:
## Word embedding representation
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_len=8

In [8]:
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 9088 5739 7350 9803]
 [   0    0    0    0 9088 5739 7350  487]
 [   0    0    0    0 9088 1182 7350 8539]
 [   0    0    0 3160 3908 1782  700 5473]
 [   0    0    0 3160 3908 1782  700 2116]
 [   0    0    0 2230 9088 6185 7350 9516]
 [   0    0    0    0 3584 5354 7856  700]]


In [9]:
## Feature representation
dim=10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_len,)))
model.add(SimpleRNN(64, return_sequences=True))
model.add(Dense(1))
model.compile('adam','mse')


d:\Data science projects\Rnn Project\venvs\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 8, 64)          │         4,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 8, 1)           │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,865 (409.63 KB)

 Trainable params: 104,865 (409.63 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 393ms/step


array([[[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
        [-0.06521025],
        [-0.13480592],
        [-0.08226265],
        [-0.02713528],
        [-0.00376983]],

       [[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
        [-0.06521025],
        [-0.13480592],
        [-0.08226265],
        [-0.02713528],
        [-0.03068573]],

       [[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
        [-0.06521025],
        [-0.13480592],
        [-0.05002629],
        [-0.07012697],
        [-0.02560089]],

       [[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
        [-0.07590565],
        [-0.09630313],
        [-0.05005074],
        [ 0.03596749],
        [-0.02750123]],

       [[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
        [-0.07590565],
        [-0.09630313],
        [-0.05005074],
        [ 0.03596749],
        [-0.02949233]],

       [[ 0.01830876],
        [-0.03032201],
        [-0.06877583],
 